name: CI Builds

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetches all submodules
      - uses: actions/setup-java@v4
        with:
          distribution: 'graalvm' # See 'Supported distributions' for available options
          java-version: '23'

      - name: Maven package
        run: ./mvnw --batch-mode --no-transfer-progress verify --file pom.xml

      - name: Get Maven project version
        id: get_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: Upload jar
          path: |
            ./target/setup-${{ steps.get_version.outputs.VERSION }}.jar

      - name: Verify .mdc files exist in jar
        run: |
          if jar tf ./target/setup-${{ steps.get_version.outputs.VERSION }}.jar | grep -q "\.mdc"; then
            echo "✅ .mdc files found in the jar"
          else
            echo "❌ No .mdc files found in the jar"
            exit 1
          fi

      - name: Upload JaCoCo coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage-report
          path: ./target/site/jacoco
          retention-days: 7