name: CI Builds

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetches all submodules
      - uses: actions/setup-java@v4
        with:
          distribution: 'graalvm' # See 'Supported distributions' for available options
          java-version: '23'

      - name: Maven package
        run: |
          ./mvnw --batch-mode --no-transfer-progress package

      - name: Get Maven project version
        id: get_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: Upload jar
          path: |
            ./target/setup-${{ steps.get_version.outputs.VERSION }}.jar

      - name: Show Jar content
        run: |
          jar tf ./target/setup-${{ steps.get_version.outputs.VERSION }}.jar
