name: CI Builds

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetches all submodules
      - uses: actions/setup-java@v4
        with:
          distribution: 'graalvm' # See 'Supported distributions' for available options
          java-version: '24'

      - name: Maven build
        run: ./mvnw --batch-mode --no-transfer-progress package surefire-report:report --file pom.xml -Pjacoco

      - name: Get Maven project version
        id: get_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Test CLI commands
        run: |
          JAR_FILE="./target/setup-${{ steps.get_version.outputs.VERSION }}.jar"
          echo "Testing CLI with $JAR_FILE"
          java -jar $JAR_FILE --help || exit 0
          java -jar $JAR_FILE init --help || exit 0
          # Run basic init commands and check exit code
          java -jar $JAR_FILE init --devcontainer || exit 0
          java -jar $JAR_FILE init --cursor java || exit 0
          java -jar $JAR_FILE init --cursor spring-boot || exit 0
          java -jar $JAR_FILE init --cursor quarkus || exit 0
          java -jar $JAR_FILE init --cursor tasks || exit 0
          java -jar $JAR_FILE init --maven || exit 0
          java -jar $JAR_FILE init --spring-cli || exit 1
          java -jar $JAR_FILE init --quarkus-cli || exit 1
          java -jar $JAR_FILE init --github-action || exit 1
          java -jar $JAR_FILE init --editorconfig || exit 1
          java -jar $JAR_FILE init --sdkman || exit 1
          java -jar $JAR_FILE init --visualvm || exit 1
          java -jar $JAR_FILE init --jmc || exit 1
          java -jar $JAR_FILE init --gitignore || exit 1
          echo "✅ CLI commands executed successfully"

      - name: Verify .mdc files exist in jar
        run: |
          if jar tf ./target/setup-${{ steps.get_version.outputs.VERSION }}.jar | grep -q "\.mdc"; then
            echo "✅ .mdc files found in the jar"
          else
            echo "❌ No .mdc files found in the jar"
            exit 1
          fi

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: setup-${{ steps.get_version.outputs.VERSION }}.jar
          path: |
            ./target/setup-${{ steps.get_version.outputs.VERSION }}.jar

      - name: Upload JaCoCo coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage-report
          path: ./target/site/jacoco
          retention-days: 7

      - name: Upload surefire reports
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: ./target/reports
          retention-days: 7